[package]
name = "thor_turtle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
turtle-graphics = { git = "https://github.com/mirsella/turtle-graphics-rs" }
